name: synthoseis
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - h5py
  - matplotlib
  - scikit-image
  - scipy
  - tqdm
  - pytables
  - plotly
  - pip:
    - bruges
    - noise
    - joblib
    - numpy==1.26.4